version: '3.4'

services:

  backend:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    container_name: app-be
    image: be_app:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./app.env
    depends_on:
      - db
    networks:
      eduamp_network:
        aliases:
          - app_be

  database:
    container_name: app-db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - mysql.env
    networks:
      eduamp_network:
        aliases:
          - app_be

networks:
  app_be: